name: Build_obfuscators
on:
  push:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug]
    runs-on: windows-latest 
    env:
      Solution_Name: Rubeus.sln                                # 替换为解决方案名

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        repository: <Github账户>/ConfuserEx2-fork
        ref: refs/heads/master
        token: ${{ secrets.REPO_ACCESS_TOKEN }}                 # 替换为自己的PAT
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2 

    - name: Setup Nuget.exe
      uses: nuget/setup-nuget@v1

    # Install Dependencies
    - name: Nuget Restore
      run: nuget restore ${{ github.workspace }}\Confuser2.sln

    - name: Build ConfuserEx2.CLI
      run: msbuild ${{ github.workspace }}\Confuser.CLI\Confuser.CLI.csproj     
      env:
        Configuration: ${{ matrix.configuration }}

    - name: Debug
      run: dir Confuser.CLI\bin\debug

    - name: Checkout Rubeus
      uses: actions/checkout@v3
      with:
        path: Rubeus-Build
        fetch-depth: 0   

    - name: Build Rubeus
      #run: msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Configuration
      run: msbuild ${{ github.workspace }}\Rubeus-Build\Rubeus\Rubeus.csproj
      env:
        Configuration: ${{ matrix.configuration }}


    - name: Run Obfuscator
      shell: cmd
      run: ${{ github.workspace }}\Confuser.CLI\bin\Debug\net461\Confuser.CLI.exe ${{ github.workspace }}\Rubeus-Build\Rubeus.crproj

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Rubeus
        path: |
          Rubeus-Build\Rubeus\bin\Debug\Rubeus.exe
          Rubeus-Build\Rubeus\bin\Debug\Confused\Rubeus.exe
